# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1-pre-2
loader_version=0.18.4
fabric_api_version=0.143.12+26.1

# Mod Properties
mod_version=0.7.1
maven_group=dev.muon
archives_base_name=dynamic-tooltips

# Deps
# forge_config_api_version=21.11.1
modmenu_version=18.0.0-alpha.6
yacl_version=
# Better Combat
# pal_version = 1.1.4+mc.1.21.11
# tiny_config_version=3.1.0